### ISSUE TITLE
Browser with web3 provider needs to be set to Rinkeby network

### ISSUE THREAD

**Issue by abcoathup** [OpenZeppelin/gsn-sample-chat_app#20]
When using the sample chat app with a browser with web3 provider (e.g. Brave with MetaMask), the provider needs to be set to Rinkeby network.

App should have messaging on the supported networks (or errors if network not supported).

Does the app even need to use the browser web3 provider at all?

**Comment by crazyrabbitLTC** [comment]
I've disabled the ability to choose another network. Too many different web3 providers to get a stable experience.
