### ISSUE TITLE
Re-enable the send button if an error occurs

### ISSUE THREAD

**Issue by spalladino** [OpenZeppelin/gsn-sample-chat_app#8]
If an error is thrown when the user sends a tx, the send button remains locked, and there is no indication of the error except on the console. Let's add a notice on the UI that an error happened, and unlock the button to send a new tx.

**Comment by crazyrabbitLTC** [comment]
I think this is already fixed. 

To test: https://gsn-chat-app.openzeppelin.com/

Try to make a transaction (for example using MetaMask), reject the transaction. It will throw an error and notify with a "click to dismiss" note beneath the send button that an error has occurred.
